version: '3.8'

services:
  api:
    build: .
    ports:
      - "${API_PORT:-8000}:8000"
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=postgresql-db
    restart: unless-stopped
    networks:
      - db_default

networks:
  db_default:
    external: true
