[pytest]
pythonpath = microservice
markers =
    integration: Test that requires real external services (LLM, DB)
testpaths = tests
asyncio_mode = auto
addopts =
    --html=reports/pytest-report.html
    --self-contained-html
